WebAI/WebAI/Controllers/CrawlerStatsController.cs
using AutoMapper;
using BusinessLogic.DTO;
using BusinessLogic.Services.Base;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using WebAI.Models;

namespace WebAI.Controllers
{
    public class CrawlerStatsController : Controller
    {

        ICrawlerStatsService crawlerStatsService = null;
        public CrawlerStatsController(ICrawlerStatsService crawlerStatsService)
        {
            this.crawlerStatsService = crawlerStatsService;
        }
        
        public IEnumerable<CrawlerStatsViewModel> GetCrawlerStats()
        {

            var stat = crawlerStatsService.GetCrawlerStats();
            Mapper.Initialize(cfg => cfg.CreateMap<CrawlerStatsDTO, CrawlerStatsViewModel>());
            return Mapper.Map<IEnumerable<CrawlerStatsDTO>, IEnumerable<CrawlerStatsViewModel>>(stat);
        }


        public ActionResult Index()
        {
            return View(GetCrawlerStats());
        }

        public ActionResult PartialCrawlerStats()
        {
             return PartialView("_crawlerStats", GetCrawlerStats());
        }

        public void ExportToCSV()
        {

        StringWriter sw = new StringWriter();

        sw.WriteLine("\"Sate name\";\"All pages in base\";\"Checked crawlers\";\"Not checked crawlers\"");

        Response.ClearContent();
        Response.AddHeader("content-disposition", "attachment;filename=Exported_CrawlerStats.csv");
            Response.ContentType = "text/csv";

            foreach (var line in GetCrawlerStats())
            {
                sw.WriteLine(string.Format("\"{0}\";\"{1}\";\"{2}\";\"{3}\"",
                                           line.Site,
                                           line.CountAllLinks,
                                           line.CountVisitedLinks,
                                           line.CountNotVisitedLinks));
            }

            Response.Write(sw.ToString());

            Response.End();
        }

    }

}

WebAI/WebAI/Controllers/PersonController.cs
using BusinessLogic.Services.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAI.Models;
using AutoMapper;
using BusinessLogic.DTO;
using Utility.Helpers;

namespace WebAI.Controllers
{
    [Authorize]
    public class PersonController : Controller
    {
        IPersonService _personService = null;
        IMapper _mapper = null;
        
        
        public PersonController(IPersonService personService, IMapper mapper)
        {
            _personService = personService;
            _mapper = mapper;
        }
  
        public ActionResult PersonList()
        {
            return View(GetPersons());
        }

        public ActionResult KeyWordList()
        {
            int defaultPersonId = 0;
            var persons = GetPersons();

            if (persons.Count() != 0)
                defaultPersonId = PersonIdRemember.Id != 0 ? PersonIdRemember.Id : persons.FirstOrDefault().Id;

            ViewBag.Persons = persons;
            ViewBag.DefaultPersonId = defaultPersonId;
            ViewBag.KeyWords = GetKeyWords(defaultPersonId);

            if (defaultPersonId != 0)
                ViewBag.Person = _personService.GetPersonById(defaultPersonId).Name;

            ViewBag.DefaultPerson = GetPersonById(PersonIdRemember.Id);

            return View();
        }

        public ActionResult FIlteredKeyWord(PersonViewModel person)
        {
            ViewBag.Person = _personService.GetPersonById(person.Id).Name;
            ViewBag.SelectedPersonId = person.Id;
            PersonIdRemember.Id = person.Id;
            return PartialView("_KeyWordList", GetKeyWords(person.Id));
        }

        IEnumerable<PersonViewModel> GetPersons()
        {
            var person = _personService.GetPersons();
            return _mapper.Map<IEnumerable<PersonDTO>, IEnumerable<PersonViewModel>>(person);
        }

        PersonViewModel GetPersonById(int id)
        {
            var person = _personService.GetPersonById(id);
            return _mapper.Map<PersonDTO, PersonViewModel>(person);
        }

        IEnumerable<KeyWordViewModel> GetKeyWords()
        {
            var keyWord = _personService.GetKeyWords();
            return _mapper.Map<IEnumerable<KeyWordDTO>, IEnumerable<KeyWordViewModel>>(keyWord);
        }

        IEnumerable<KeyWordViewModel> GetKeyWords(int id)
        {
            var keyWord = _personService.GetKeyWordsForPerson(id);
            return _mapper.Map<IEnumerable<KeyWordDTO>, IEnumerable<KeyWordViewModel>>(keyWord);
        }

        [HttpGet]
        public ActionResult AddPerson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPerson(PersonViewModel newPerson)
        {
            _personService.AddPerson(_mapper.Map<PersonViewModel, PersonDTO>(newPerson));
            return RedirectToAction("PersonList");
        }
        

        [HttpGet]
        public ActionResult ChangePerson(int id)
        {
            var personDTO = _personService.GetPersonById(id);
            return View(_mapper.Map<PersonDTO, PersonViewModel>(personDTO));
        }


        [HttpPost]
        public ActionResult ChangePerson(PersonViewModel personToChange)
        {
            var personDTO = _mapper.Map<PersonViewModel, PersonDTO>(personToChange);
            _personService.ChangePerson(personDTO);
            return RedirectToAction("PersonList");
        }

        public ActionResult DeletePerson(int id)
        {
            _personService.DeletePersonById(id);
            return RedirectToAction("PersonList");
        }

        [HttpGet]
        public ActionResult AddKeyWord(int id)
        {
            ViewBag.PersonId = id;
            ViewBag.Person = _personService.GetPersonById(id).Name;
            return View();
        }

        [HttpPost]
        public ActionResult AddKeyWord(KeyWordViewModel newKeyWord)
        {
            PersonIdRemember.Id = newKeyWord.PersonId;
            _personService.AddKeyWord(_mapper.Map<KeyWordViewModel, KeyWordDTO>(newKeyWord));
            return RedirectToAction("KeyWordList");
        }

        [HttpGet]
        public ActionResult ChangeKeyWord(int id)
        {
            var keyWordDTO = _personService.GetKeyWordById(id);
            return View(_mapper.Map<KeyWordDTO, KeyWordViewModel>(keyWordDTO));
        }


        [HttpPost]
        public ActionResult ChangeKeyWord(KeyWordViewModel keyWordToChange)
        {
            PersonIdRemember.Id = keyWordToChange.PersonId;
            var keyWordDTO = _mapper.Map<KeyWordViewModel, KeyWordDTO>(keyWordToChange);
            _personService.ChangeKeyWord(keyWordDTO);
            return RedirectToAction("KeyWordList");
        }

        public ActionResult DeleteKeyWord(int id)
        {
            PersonIdRemember.Id = _personService.GetKeyWordById(id).PersonId;
            _personService.DeleteKeyWordById(id);
            return RedirectToAction("KeyWordList");
        }
    }
}

WebAI/WebAI/Controllers/SiteController.cs
using BusinessLogic.Services;
using BusinessLogic.Services.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAI.Models;
using AutoMapper;
using BusinessLogic.DTO;

namespace WebAI.Controllers
{
    [Authorize]
    public class SiteController : Controller
    {
        ISiteService _siteService = null;
        IMapper _mapper = null;
        
        public SiteController(ISiteService siteService, IMapper mapper)
        {
            _siteService = siteService;
            _mapper = mapper;
        }
        
        public ActionResult Index()
        {
            return View(GetSites());
        }

        IEnumerable<SiteViewModel> GetSites()
        {
            var site = _siteService.GetSites();
            return _mapper.Map<IEnumerable<SiteDTO>, IEnumerable<SiteViewModel>>(site);
        }
        
        [HttpGet]
        public ActionResult Add()

        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(SiteViewModel newSite)
        {
            _siteService.AddSite(_mapper.Map<SiteViewModel, SiteDTO>(newSite));
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var siteDTO = _siteService.GetSiteById(id);
            return View(_mapper.Map<SiteDTO,SiteViewModel>(siteDTO));
        }

        [HttpPost]
        public ActionResult Edit (SiteViewModel siteToChange)
        {
            var siteDTO = _mapper.Map<SiteViewModel, SiteDTO>(siteToChange);
            _siteService.ChangeSite(siteDTO);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _siteService.DeleteSiteById(id);
            return RedirectToAction("Index");
        }
    }
}

WebAI/WebAI/Views/Shared/_AIMenu.cshtml
<div class="col-md-3" style="background-color:lightgray; padding: 120px 30px; height: 500px">
    <ul>
        <li>
            @Html.ActionLink("Управление справочниками", "Index", "Home")
            <ul>
                <li>@Html.ActionLink("Личности", "PersonList", "Person")</li>
                <li>@Html.ActionLink("Ключевые слова", "KeyWordList", "Person")</li>
                <li>@Html.ActionLink("Сайты", "Index", "Site")</li>
            </ul>
        </li>
        <li>@Html.ActionLink("Статистика краулера", "Index", "CrawlerStats")</li>
        <li>@Html.ActionLink("Добавить пользователя", "UserRegistration", "Account")</li>
        
    </ul>
</div>

WebAI/WebAI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{ 
    bool isLoginForm = ViewBag.IsLoginForm != null ? ViewBag.IsLoginForm : false;
}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
   @Styles.Render("~/Content/css")
   @Scripts.Render("~/bundles/modernizr")
   @Scripts.Render("~/Scripts/jquery-3.1.1.min.js")
   @Scripts.Render("~/Scripts/jquery.validate.min.js")
   @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" @*style="background-color:burlywood"*@>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SpaceBrains", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if (!isLoginForm)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.Action("CurrentUser", "Account")
                        </li>
                    </ul>
                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
           
            @*<div class="row">
        <div class="col-md-3" style="background-color:lightgray; padding: 120px 30px; height: 500px">
            <ul>
                <li>
                    @Html.ActionLink("Управление справочниками", "Index", "Home")
                    <ul>
                        <li>@Html.ActionLink("Личности", "PersonList", "Person")</li>
                        <li>@Html.ActionLink("Ключевые слова", "KeyWordList", "Person")</li>
                        <li>@Html.ActionLink("Сайты", "Index", "Site")</li>
                    </ul>
                </li>
                <li>
                    @Html.ActionLink("Статистика краулера", "Statistics", "Home")
                </li>
            </ul>


        </div>
        <div class="col-md-8">
            @RenderBody()
        </div>
    </div>*@

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year – SpaceBrainsProject</p>
    </footer>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

WebAI/WebAI/Views/Shared/_SuperAIMenu.cshtml
<div class="col-md-3" style="background-color:lightgray; padding: 120px 30px; height: 500px">
    <ul>
       
        <li>@Html.ActionLink("Добавить Администратора", "AdminRegistration", "Account")</li>
    </ul>
</div>